modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/"

[[mods]]
modId="heartsmod"
version="1.0.0"
displayName="Hearts Mod"
authors="Silv"
description='''Pierde medio corazón al morir y gana un corazón al matar a otro jugador.'''

[[dependencies.heartsmod]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.heartsmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
